### ISSUE TITLE
Zoom bar calculations incorrect when selecting from a larger sample group and choosing the bottom rows

### ISSUE THREAD

**Issue by frano-m** [ucscXena/ucsc-xena-client#405]
![image.png](https://images.zenhubusercontent.com/5ac463024b5806bc2bcd91dd/96f67a77-cdb4-44bf-8f7d-6f1c266d4d0c)

**Comment by NoopDog** [comment]
@frano-m can you find a test case for this on prod so we can prove it is fixed in stage. Thanks!

**Comment by maryjgoldman** [comment]
This is still broken it looks like. See http://cc.xenabrowser.net/heatmap/?bookmark=5d059a700cbf8b9f7d3080013bdc0790. Says there are 10518 samples but zoomed to 6079 - 10519 (i.e. one more than how many samples are in view).

![Screen Shot 2019-04-15 at 11.37.27 AM.png](https://images.zenhubusercontent.com/5b34f42a89c1fc1ffe8ce9a6/371aa305-1db9-47f0-aad6-0a59b969e764)

**Comment by NoopDog** [comment]
@maryjgoldman this might be a different bug. Will take a look. @frano-m can you give a test case for the original bug? Thanks. D

**Comment by frano-m** [comment]
@maryjgoldman try this example https://xenabrowser.net/heatmap/?bookmark=80904dd5f8129a1dc1d8e5b8a20527c3
zoom a large % of the samples and all the way to the last sample..

**Comment by maryjgoldman** [comment]
I see. Yes, you can't get the last sample on production.

The trouble is when I do this same exact action (zoom a large % of the samples and all the way to the last sample) on http://cc.xenabrowser.net/heatmap/, I can get one more than the total samples when zooming in about 1 out of 6 times with a fresh tab. 

Putting on my big-picture hat ... I think having the zoom have one extra sample seems like an ok bug since a) it doesn't break the browser as far as I can tell and b) it's not every time. And this fix is important since current functionality is pretty blocking if you're trying to zoom to the last few samples.

Let's release this fix and I'll open a new issue.
